### ISSUE TITLE
Support default login URI

### ISSUE THREAD

**Issue by MorrisonCole** [terraform-providers/terraform-provider-auth0#1]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

---

### Description

There are two ways to configure this feature in Auth0 - as a tenant default and per-application.

Auth0 tenants have a 'Tenant Login URI' configuration field:
![image](https://user-images.githubusercontent.com/963368/74615355-4cc7dc00-5163-11ea-982e-1be8059cc23c.png)

Auth0 clients have an 'Application Login URI' configuration field:
![image](https://user-images.githubusercontent.com/963368/74615316-eba00880-5162-11ea-9c89-1f3c9f83ef63.png)

### New or Affected Resource(s)

* `auth0_tenant.tenant_login_uri` (or similar)
* `auth0_client.application_login_uri` (or similar)

### References

* https://auth0.com/docs/universal-login/default-login-url

**Comment by alexkappa** [comment]
Hi @MorrisonCole thank you for the detailed report. I've taken a stab at adding this (see: #2). I will be merging this in soon.

**Comment by MorrisonCole** [comment]
Thanks a bunch @alexkappa! 

Just wondering if you have an expectation for when this (and other changes) might be released in a version past 0.5.1? I notice there have been some tags since that version, but I don't think they've been published 💭

**Comment by adamu** [comment]
I think this project was moved to https://github.com/alexkappa/terraform-provider-auth0/releases

**Comment by alexkappa** [comment]
@MorrisonCole there's been a number of releases since then:
https://releases.hashicorp.com/terraform-provider-auth0/

@adamu I will be keeping both repos up to date as best I can, but releases will have a priority here.

**Comment by MorrisonCole** [comment]
> @MorrisonCole there's been a number of releases since then:
> https://releases.hashicorp.com/terraform-provider-auth0/

Ah, apologies!

I was misled by the GitHub releases with no description or artefacts in this repository. I appreciate the migration is probably difficult, so I'll keep up to date with both for now 😄

**Comment by alexkappa** [comment]
No you are right, there was no communication from my part so I am to blame for the confusion. Take care!
