### ISSUE TITLE
0.7.0 fails plan with "Error: missing expected ["

### ISSUE THREAD

**Issue by SpamapS** [terraform-providers/terraform-provider-auth0#10]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

We tend to run a little behind releases, so we're on 0.12.20

```
$ terraform version
Terraform v0.12.20
+ provider.auth0 v0.7.0
+ provider.aws v2.54.0
+ provider.cloudflare v1.18.1
+ provider.external v1.2.0
+ provider.helm v1.0.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.mysql v1.9.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.sops v0.5.0
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* auth0_client

### Terraform Configuration Files

```hcl
resource "auth0_client" "client" {
  name        = "app"
  description = "Authentication for app"
  app_type    = "regular_web"
  callbacks = [
    local.cf_access_callback
  ]

  addons {
    samlp {
      mappings = {
        email = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
        name  = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      }

      create_upn_claim                   = false
      passthrough_claims_with_no_mapping = false
      map_unknown_claims_as_is           = false
      map_identities                     = false
      name_identifier_format             = "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"

      name_identifier_probes = [
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
      ]
    }
  }
}

resource "auth0_connection" "connection" {
  name     = "app-google-auth"
  strategy = "google-oauth2"

  options {
    client_id     = var.gsuite_client_id
    client_secret = var.gsuite_client_secret
  }

  enabled_clients = [
    auth0_client.client.id
  ]
}

```

### Debug Output

Cannot share the whole debug out, but here is what I think is the relevant section. It appears that the state produced by previous versions (0.6.0 in our case) can't be used by 0.7.0.

```
2020-03-23T21:34:09.855-0700 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: 2020/03/23 21:34:09 [WARN] unexpected type cty.List(cty.Object(map[string]cty.Type{"length":cty.Number, "time_step":cty.Number})) for map in json state
2020/03/23 21:34:09 [ERROR] module.top.module.auth0: eval: *terraform.EvalReadState, err: missing expected [
2020/03/23 21:34:09 [ERROR] module.top.module.auth0: eval: *terraform.EvalSequence, err: missing expected [
```

### Panic Output

N/A

### Expected Behavior

plan should work

### Actual Behavior

See title

### Steps to Reproduce

1. `terraform apply` an auth0_client with 0.6.0
2. `terraform init -upgrade` to get 0.7.0
3. `terraform plan`

### Important Factoids

We just started using auth0 a few weeks ago so it's possible we are a corner case of some kind that had stuff only from 0.6.0.

### References

N/A

* #0000

**Comment by sharkyze** [comment]
I am having the same issue using the provider v0.8.0.

I am not sure which resource is failing exactly, the debug output changes on every run.

```
auth0_rule.link_users_by_email_with_metadata: Refreshing state... [id=rul_3vjAqo6d5KyY5PQk]
auth0_rule.add_organisation_to_tokens: Refreshing state... [id=rul_kLlTR4RpIR8NEGSY]
2020/03/24 18:24:06 [ERROR] <root>: eval: *terraform.EvalReadState, err: missing expected [
2020/03/24 18:24:06 [ERROR] <root>: eval: *terraform.EvalSequence, err: missing expected [
```

**Comment by xsaamiir** [comment]
More details and a workaround are on this issue: https://github.com/alexkappa/terraform-provider-auth0/issues/157

This answer solved my issue: https://github.com/alexkappa/terraform-provider-auth0/issues/157#issuecomment-603440102

**Comment by alexkappa** [comment]
Closing this as there already is a ticket tracking the bug.
