### ISSUE TITLE
trigger id send_phone_message is blocked

### ISSUE THREAD

**Issue by ninja-** [terraform-providers/terraform-provider-auth0#14]
This is verifier list that lacks send_phone_message: https://github.com/terraform-providers/terraform-provider-auth0/blob/e278f239cfe5d627831f730e9b9eea7a13cc5265/auth0/resource_auth0_hook.go#L41

And on line 50 we see mention that this trigger should be allowed with others.

**Comment by aslafy-z** [comment]
@ninja- this issue can now be closed.
