### ISSUE TITLE
refresh_token field for client

### ISSUE THREAD

**Issue by rienafairefr** [terraform-providers/terraform-provider-auth0#19]
### Description

I noticed the provider does not support (AFAIK) the refresh token rotation for clients
In https://auth0.com/docs/api/management/v2#!/Clients/get_clients, we see there is an added refresh_token field, with this kind of format:
    "refresh_token": {
      "rotation_type": "non-rotating",
      "expiration_type": "non-expiring",
      "leeway": 0,
      "token_lifetime": 2592000
    }
Expect a PR, I guess, if i manage to write some go. Wish me luck ^^

### New or Affected Resource(s)

* auth0_client

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Indeed, these fields are new. I've only recently added support for them in https://github.com/go-auth0/auth0/pull/120.

It should be straightforward to implement, feel free to use the surrounding code as inspiration. Also don't hesitate to ask!

**Comment by tj111** [comment]
Just a bump on this, we are looking to manage this through terraform as well.

**Comment by alexkappa** [comment]
Just merged alexkappa/terraform-provider-auth0#255 from @rienafairefr. We should soon have a 0.13.0 release.
