### ISSUE TITLE
{domain}/oauth/token Forbidden in version 0.12.2

### ISSUE THREAD

**Issue by hknerts** [terraform-providers/terraform-provider-auth0#24]
### Description

when calling /oauth/token endpoint for authentication, we realised that the audience parameter is missing because it gives 403 Forbidden error.

audience paramater is missing or maybe not end with "/"

### Affected Resource(s)

* auth0_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a [Github Gist](https://gist.github.com/) instead.
```

### Expected Behavior

200

### Actual Behavior

403

### Steps to Reproduce

check audience paramater

1. `terraform apply`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @hknerts have you specified a domain correctly? The audience uses is made up from the domain parameter internally.

**Comment by hknerts** [comment]
Yes i copied it from auth0 management ui.  (Domain, clientid, client secret) Also, i defined all permission to app.

**Comment by hknerts** [comment]
How do you made from domain? I tried with my credentials and audience via postman. Audience is  {domain}/api/v2. It was succesfull.

**Comment by alexkappa** [comment]
Could you paste (part of) your terraform configuration? I can't help you much without it.

Also, please run terraform with the `TF_LOG=DEBUG` and `AUTH0_DEBUG=1` environment variables enabled and paste the output in a gist.

**Comment by hknerts** [comment]
i think something is changed from your side. i executed same code now.it works now.
Did you changed somthing ? =)

**Comment by alexkappa** [comment]
No, I'm afraid not :) Happy that you've worked it out!
