### ISSUE TITLE
Unable to edit default database

### ISSUE THREAD

**Issue by owahab** [terraform-providers/terraform-provider-auth0#4]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.auth0 v0.5.1

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "database" {
  name = "Username-Password-Authentication"
  strategy = "auth0"

  options {
    password_policy = "strong"
  }
}
```

### Expected Behavior

Default database updated with the chosen `password_policy`

### Actual Behavior

```
Error: 409 Conflict: A connection with the same name already exists

  on auth0_connections.tf line 1, in resource "auth0_connection" "database":
   1: resource "auth0_connection" "database" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by owahab** [comment]
Not sure if it's the same issue or a separate one but the same applies to default connection `google-oauth2`.

**Comment by alexkappa** [comment]
Hi @owahab, this is common with pre-generated resources. For the time being, I would advise importing the resource into your terraform state and making the updates then.

There is an open issue and ongoing discussion on dealing with default resources (see https://github.com/alexkappa/terraform-provider-auth0/pull/172). If we settle that way we may be able to support this use case better in the future.

**Comment by alexkappa** [comment]
@owahab, on your first example you use the same name as an existing database. I believe the `auth0` type connections can be defined multiple times. You just need to use a unique name.
