### ISSUE TITLE
Unable to change `strategy_version` for windowslive connection

### ISSUE THREAD

**Issue by owahab** [terraform-providers/terraform-provider-auth0#5]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.auth0 v0.5.1

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "microsoft" {
  name = "windowslive"
  strategy = "windowslive"
  is_domain_connection = true
  strategy_version = 2

  options {
    client_id = var.microsoft_azure_client_id
    client_secret = var.microsoft_azure_client_secret
    tenant_domain = var.microsoft_azure_tenant_domain
  }
}
```

### Expected Behavior

Windowslive connection uses the new 

### Actual Behavior

Error: Unsupported argument

  on auth0_connections.tf line 23, in resource "auth0_connection" "microsoft":
  23:   strategy_version = 2

### Steps to Reproduce

1. `terraform apply`

### References

![Screenshot 2020-02-18 at 17 09 58](https://user-images.githubusercontent.com/125080/74754440-e54c8200-5271-11ea-8498-114d6f1c21f9.png)

**Comment by alexkappa** [comment]
This issue is addressed, please try the v0.8.0 release.
